---
name: Error-Exception
version: 1.0
author:
  - 'Stephen Vance <steve@vance.com>'
abstract: Combines Error and Exception::Class with correct stringication
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Error: 0
  Exception::Class: 0
build_requires:
  Module::Locate: 0
  Test::More: 0
  Test::Unit: 0
provides:
  Error::Exception:
    file: lib/Error/Exception.pm
    version: 1.0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
